name: test WSL

on:
  workflow_dispatch
  
jobs:
  wsl_run:
    runs-on: windows-latest
    
    steps:
      - shell: pwsh
        run: |
            $wslupd = wsl --update --web-download | Out-String
            $wslupd
            if ($wslupd) {
              wsl --version
              wsl --set-default-version 1
              wsl --install --distribution Ubuntu-20.04 --web-download --no-launch
            }  
